services:
  - type: web
    name: qrsona-backend
    runtime: go
    buildCommand: cd backend && go build -o main .
    startCommand: cd backend && ./main
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: GIN_MODE
        value: release
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /api/health
